import type {Metadata} from 'next';
import {Geist, Geist_Mono, Jacquard_24, Metamorphous} from 'next/font/google';
import './globals.css';
import Nav from './nav/Nav';

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
});

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
});

const jacquard24 = Jacquard_24({
	variable: '--font-jacquard-24',
	subsets: ['latin'],
	weight: '400',
});

const metamorphous = Metamorphous({
	variable: '--font-metamorphous',
	subsets: ['latin'],
	weight: '400',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} ${jacquard24.variable} ${metamorphous.variable}`}
			>
				<Nav />
				{children}
			</body>
		</html>
	);
}
